language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  apt:
    packages:
    - spamassassin
before_script:
 - sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/spamassassin
services: spamassassin